### ISSUE TITLE
NugetContentRestoreTask is added to random project

### ISSUE THREAD

**Issue by MistyKuu** [panchilo/MSBuild.NugetContentRestore#11]
Hey,
Get-Project is returning random project. Change it to be $project instead

**Comment by panchilo** [comment]
Works for my @MistyKuu. And it should work for you too. Check out the documentation here:
[https://docs.nuget.org/consume/package-manager-console-powershell-reference](https://docs.nuget.org/consume/package-manager-console-powershell-reference).
Want to sent me what you are getting, I might be able to help.

**Comment by MistyKuu** [comment]
Hey, sorry I have forgotten about this library. I went with the approach of using msbuild and nuget build feature. Please ignore this one as I could've done something wrong

**Comment by panchilo** [comment]
Not a problem. Thank you for closing the issue.
