### ISSUE TITLE
MSBuild.NugetContentRestore should be marked as a developmentDependency

### ISSUE THREAD

**Issue by jamesathey** [panchilo/MSBuild.NugetContentRestore#14]
In other words, projects that use NugetContentRestore should not demand that _their_ dependencies install NugetContentRestore as well.

MSBuild.NugetContentRestore should have `<developmentDependency>true</developmentDependency>` in the `<metadata>` section of its nuspec file, [which would ensure that the developmentDependency="true" attribute is included in the <package id="MSBuild.NugetContentRestore" /> line in packages.config](https://docs.nuget.org/create/nuspec-reference).

[As NuGet's documentation explains:](https://docs.nuget.org/Release-Notes/NuGet-2.7#development-only-dependencies)

> It allows package authors to declare dependencies that were only used at development time and don't require package dependencies. By adding a developmentDependency="true" attribute to a package in packages.config, nuget.exe pack will no longer include that package as a dependency.

**Comment by devmonkey22** [comment]
I'm about to submit a PR for this change, included with some other work I was adding.
Hopefully @panchilo approves of the change :+1:

**Comment by benjaivan** [comment]
@jamesathey and @devmonkey22 - I'll review your change this week and release the new version as well. Unfortunately, this project doesn't have a CI plan out there. That's why it will take a little longer than it should. Hope you understand the associated delay.

**Comment by panchilo** [comment]
@jamesathey and @devmonkey22 - I'll review your change this week and release the new version as well. Unfortunately, this project doesn't have a CI plan out there. That's why it will take a little longer than it should. Hope you understand the associated delay.

**Comment by daryllabar** [comment]
Shouldn't this be closed?

**Comment by panchilo** [comment]
Correct, @daryllabar. Thank you!
