### ISSUE TITLE
Is your Usage missing a step?

### ISSUE THREAD

**Issue by michaelgwelch** [panchilo/MSBuild.NugetContentRestore#7]
Here is my expectation based on your README.

I am already using some NuGet packages (that include binaries that I don't want to check into source control). I would like a restore to copy content to my project folders. So I add your package as explained and then magically whenever a restore of one of my packages is done, the content is copied to the project directory.

But, I am not seeing any copy performed. Is there some other step I need to perform to hook up your package?

**Comment by michaelgwelch** [comment]
I just read your readme.txt and it says I should see a BeforeBuild step. I do not see that.

I'm using version 0.1.6

**Comment by panchilo** [comment]
@michaelgwelch, I am sorry my solution is not working out of the box for you as you expected.
Let me see if I understand the issue. You mentioned a keyword when you said "... (that include BINARIES that ...". The main purpose of this solution is to automatically restore client-side artifacts (like the ones provided by packages like angular and bootstrap) to the Project folder. This is why, the folders (or the content of the folders) that will be copied are predefined in the code; these are "Scripts", "Images", "fonts", "content" (always under "Content" folder in the nuget package folder).
Now, that being said, if there is any other folder your package has (say, "lib") and that folder is within "Content" folder, you can always add it using AdditionalFolders attribute in your .csproj file.

Please read issue #6 for more information. I believe that might be helpful too. 

And please let me know if you were able to figure it out and if not, just send an example and I'll take a look at it...

**Comment by michaelgwelch** [comment]
Ok, the binaries that I'm copying are cadfiles that we are using for integration tests. We don't want these cadfiles checked into our source so they are in a Nuget package. We only need them for our integration tests. So it would be highly desirable for them to be copied into a known location in our project upon project restore.

They are stored in content/cadfiles in our package. 

So perhaps the issue is that your task doesn't recurse folders under content? It is simply looking for files directly under content?

I looked at #6. I wish I could understand powershell/Nuget scripts better as that would probably answer my question.

**Comment by michaelgwelch** [comment]
One other thing I noticed after reading #6 again. It mentions this line:

```shell
<NugetContentRestoreTask SolutionDir="$(SolutionDir)" ProjectDir="$(ProjectDir)" AdditionalFolders="bin;lib" />
```

Where should I see this? I don't see it added to any of my files as I checked with `git status` and `git diff`.

**Comment by michaelgwelch** [comment]
@panchilo I have much more info for you now. I did a `git diff` and noticed errors in my csproj files. 

Here is a snippet

```
<Error Condition="!Exists('..\packages\MSBuild.NugetContentRestore.0.1.6\build\net40\MSBuild.NugetContentRestore.targets')"
```

Let me reset my project back to a known good state and try re-adding your nuget package.

It is definitely in my packages folder.

**Comment by panchilo** [comment]
@michaelgwelch you are def in the right direction. Once you install my package again, you should see the BeforeBuild MSBuild Task and in there, you should see a line like this:

    <NugetContentRestoreTask SolutionDir="$(SolutionDir)" ProjectDir="$(ProjectDir)" />

The only thing you need to do, is to edit that line so it looks like this:

    <NugetContentRestoreTask SolutionDir="$(SolutionDir)" ProjectDir="$(ProjectDir)" AdditionalFolders="cadfiles" />

Hope this helps. Let me know how it goes...

**Comment by michaelgwelch** [comment]
@panchilo Here is what is being added to my csproj file

```
  <Import Project="$(SolutionDir)\.nuget\NuGet.targets" Condition="Exists('$(SolutionDir)\.nuget\NuGet.targets')" />
  <Import Project="..\packages\MSBuild.NugetContentRestore.0.1.6\build\net40\MSBuild.NugetContentRestore.targets" Condition="Exists('..\packages\MSBuild.NugetContentRestore.0.1.6\build\net40\MSBuild.NugetContentRestore.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\MSBuild.NugetContentRestore.0.1.6\build\net40\MSBuild.NugetContentRestore.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\MSBuild.NugetContentRestore.0.1.6\build\net40\MSBuild.NugetContentRestore.targets'))" />
  </Target>
```

No idea why this is happening. Your package is indeed being installed in the packages folder. 

I guess I better make sure I'm running the latest Nuget, etc.

I'm using VS2012 if that makes a difference.

**Comment by panchilo** [comment]
@michaelgwelch now I know why this is not working for you. My package contains a MSBuild Task that is automatically executed BeforeBuild. But you have nuget configured with MSBuild-Integrated Package Restore. The later method of using nuget has been sort of deprecated exactly because of the issue you are currently having (in a way). Please read [this article](http://docs.nuget.org/docs/workflows/migrating-to-automatic-package-restore) and migrate to Automatic Package Restore. My package should working after doing this.

Hope this helps...

**Comment by panchilo** [comment]
@michaelgwelch Please let me know if you were able to make it work so I can close this issue. Tks.-

**Comment by michaelgwelch** [comment]
@panchilo I was able to successfully convert to Automatic Package Restore per the article you sent me. I tested it as they suggest (I deleted my packages folder, did a build, and everything was restored).

However, when I add your package via Nuget I still get a strange entry in the consuming project:

```
  <Import Project="..\packages\MSBuild.NugetContentRestore.0.1.6\build\net40\MSBuild.NugetContentRestore.targets" Condition="Exists('..\packages\MSBuild.NugetContentRestore.0.1.6\build\net40\MSBuild.NugetContentRestore.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\MSBuild.NugetContentRestore.0.1.6\build\net40\MSBuild.NugetContentRestore.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\MSBuild.NugetContentRestore.0.1.6\build\net40\MSBuild.NugetContentRestore.targets'))" />
  </Target>
```

I haven't had much time to troubleshoot this further. I did reset my work area and I tried re-adding your package several times with the same result.

The end result is that files are still not restored at this time.

**Comment by panchilo** [comment]
@michaelgwelch That is not an error. It is just part of the installation. It is saying "in case it can't find the DLL, show this error message". In order to check whether it ran or not, you should look at the Output Window while you are compiling your solution. Please do so and post the Output so I can take a look at it.

**Comment by michaelgwelch** [comment]
Ok, thanks for the info.

The build output shows nothing about your task at all. So I went back through all your instructions and remember I needed to tweak the NugetContentRestoreTask.

I see that the task was not added to my project.

Curiously, everytime I add your package to my test project, it actually adds the NugetContentRestoreTask to a project that my test project is dependent on but not to the test project itself. And then that other project fails to compile because I didn't add your package to that project (and don't want to).

Let me manually add NugetContentRestoreTask to my test project and see what happens.

**Comment by michaelgwelch** [comment]
Short answer: It's now working!

Here's the process I followed.

1. Reset my work area
2. Add your task via Nuget
3. Manually remove NugetContentRestoreTask from the project my test project is dependent on
4. Manually add NugetContentRestoreTask to my test project
5. Add `AdditionalFolders="content/cadfiles"` to the task.

**Comment by panchilo** [comment]
Great news, @michaelgwelch. Keep in mind that, in order to tell Nuget Console in Visual Studio to which project the Nuget Package should be installed on, you have to select the project on the top right side of the console. This will help you avoid the manual work next time.

**Comment by michaelgwelch** [comment]
I actually wasn't using the console. I write click on my test project, and click `Manage Nuget Packages`. Then I choose your package and select Install. The package is downloaded. An entry is added to packages.config correctly. It updates the project file with the [stuff from above](https://github.com/panchilo/MSBuild.NugetContentRestore/issues/7#issuecomment-71699726) but then adds the NugetContentRestoreTask to the wrong project. 

I'll try installing from the console to see if that makes a difference.

**Comment by michaelgwelch** [comment]
When I install from the console, everything works properly.

**Comment by panchilo** [comment]
Glad to hear everything is working fine now. Going to close this issue. Tks.-

**Comment by michaelgwelch** [comment]
@panchilo do the symptoms I'm talking about sound like a bug in Nuget itself?

**Comment by panchilo** [comment]
@michaelgwelch I can't tell for sure. I would have to investigate deeper what's the procedure that window follows. In order to have the package automatically installed in BeforeBuild Task, I created an install.ps PowerShell Script. This is script is definitely called by nuget when you use the Console. I'll find out if this is also called by that window or not and let you know.
